/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Address = IDL.Record({
  'city' : IDL.Text,
  'addressLabel' : IDL.Text,
  'address' : IDL.Text,
  'pincode' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MedicineCategory = IDL.Variant({
  'osteoporosis' : IDL.Null,
  'antiFungal' : IDL.Null,
  'antiViral' : IDL.Null,
  'vaccine' : IDL.Null,
  'otcProducts' : IDL.Null,
  'hepatitis' : IDL.Null,
  'diabetesCare' : IDL.Null,
  'surgicalDevices' : IDL.Null,
  'transplant' : IDL.Null,
  'weightLoss' : IDL.Null,
  'antiCancer' : IDL.Null,
  'nephrology' : IDL.Null,
  'general' : IDL.Null,
  'infertility' : IDL.Null,
  'arthritis' : IDL.Null,
  'heartDisease' : IDL.Null,
  'skinDisease' : IDL.Null,
  'bloodDisorders' : IDL.Null,
  'hivAids' : IDL.Null,
  'cardiacCare' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Bool,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Text,
  'category' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'stockStatus' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : MedicineCategory,
  'requiresPrescription' : IDL.Bool,
  'price' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'verified' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
  'received' : IDL.Null,
  'packed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'upi' : IDL.Null,
  'card' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const OrderItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const OrderView = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'prescription' : IDL.Opt(ExternalBlob),
  'totalAmount' : IDL.Float64,
  'timestamp' : Time,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
});
export const UserProfileView = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'addresses' : IDL.Vec(Address),
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAddress' : IDL.Func([Address], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        MedicineCategory,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'deleteAddress' : IDL.Func([Address], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPostsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryIndex' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(MedicineCategory, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(OrderView)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [MedicineCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(OrderView)], ['query']),
  'getUserProfile' : IDL.Func([], [UserProfileView], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Text, PaymentMethod, IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'publishBlogPost' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'unpublishBlogPost' : IDL.Func([IDL.Text], [], []),
  'updateAddress' : IDL.Func([Address, Address], [], []),
  'updateBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        MedicineCategory,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Address = IDL.Record({
    'city' : IDL.Text,
    'addressLabel' : IDL.Text,
    'address' : IDL.Text,
    'pincode' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MedicineCategory = IDL.Variant({
    'osteoporosis' : IDL.Null,
    'antiFungal' : IDL.Null,
    'antiViral' : IDL.Null,
    'vaccine' : IDL.Null,
    'otcProducts' : IDL.Null,
    'hepatitis' : IDL.Null,
    'diabetesCare' : IDL.Null,
    'surgicalDevices' : IDL.Null,
    'transplant' : IDL.Null,
    'weightLoss' : IDL.Null,
    'antiCancer' : IDL.Null,
    'nephrology' : IDL.Null,
    'general' : IDL.Null,
    'infertility' : IDL.Null,
    'arthritis' : IDL.Null,
    'heartDisease' : IDL.Null,
    'skinDisease' : IDL.Null,
    'bloodDisorders' : IDL.Null,
    'hivAids' : IDL.Null,
    'cardiacCare' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Bool,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Text,
    'category' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'stockStatus' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : MedicineCategory,
    'requiresPrescription' : IDL.Bool,
    'price' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'verified' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
    'received' : IDL.Null,
    'packed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'cod' : IDL.Null,
    'upi' : IDL.Null,
    'card' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const OrderItem = IDL.Record({
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const OrderView = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'prescription' : IDL.Opt(ExternalBlob),
    'totalAmount' : IDL.Float64,
    'timestamp' : Time,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
  });
  const UserProfileView = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'addresses' : IDL.Vec(Address),
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAddress' : IDL.Func([Address], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          MedicineCategory,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'deleteAddress' : IDL.Func([Address], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPostsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryIndex' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(MedicineCategory, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(OrderView)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [MedicineCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(OrderView)], ['query']),
    'getUserProfile' : IDL.Func([], [UserProfileView], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Text, PaymentMethod, IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'publishBlogPost' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'unpublishBlogPost' : IDL.Func([IDL.Text], [], []),
    'updateAddress' : IDL.Func([Address, Address], [], []),
    'updateBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          MedicineCategory,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };