/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'city' : string,
  'addressLabel' : string,
  'address' : string,
  'pincode' : bigint,
}
export interface BlogPost {
  'id' : string,
  'status' : boolean,
  'coverImageUrl' : string,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'author' : string,
  'category' : string,
}
export type ExternalBlob = Uint8Array;
export type MedicineCategory = { 'osteoporosis' : null } |
  { 'antiFungal' : null } |
  { 'antiViral' : null } |
  { 'vaccine' : null } |
  { 'otcProducts' : null } |
  { 'hepatitis' : null } |
  { 'diabetesCare' : null } |
  { 'surgicalDevices' : null } |
  { 'transplant' : null } |
  { 'weightLoss' : null } |
  { 'antiCancer' : null } |
  { 'nephrology' : null } |
  { 'general' : null } |
  { 'infertility' : null } |
  { 'arthritis' : null } |
  { 'heartDisease' : null } |
  { 'skinDisease' : null } |
  { 'bloodDisorders' : null } |
  { 'hivAids' : null } |
  { 'cardiacCare' : null };
export interface OrderItem { 'productId' : string, 'quantity' : bigint }
export type OrderStatus = { 'verified' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null } |
  { 'received' : null } |
  { 'packed' : null };
export interface OrderView {
  'id' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'paymentMethod' : PaymentMethod,
  'prescription' : [] | [ExternalBlob],
  'totalAmount' : number,
  'timestamp' : Time,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
}
export type PaymentMethod = { 'cod' : null } |
  { 'upi' : null } |
  { 'card' : null };
export interface Product {
  'id' : string,
  'stockStatus' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : MedicineCategory,
  'requiresPrescription' : boolean,
  'price' : number,
}
export type Time = bigint;
export interface UserProfileView {
  'name' : string,
  'email' : string,
  'addresses' : Array<Address>,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAddress' : ActorMethod<[Address], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'createProduct' : ActorMethod<
    [string, string, number, MedicineCategory, boolean, boolean, string],
    string
  >,
  'deleteAddress' : ActorMethod<[Address], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryIndex' : ActorMethod<
    [],
    Array<[MedicineCategory, Array<string>]>
  >,
  'getOrder' : ActorMethod<[string], [] | [OrderView]>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[MedicineCategory], Array<Product>>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getUserOrders' : ActorMethod<[], Array<OrderView>>,
  'getUserProfile' : ActorMethod<[], UserProfileView>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [Array<OrderItem>, string, PaymentMethod, [] | [ExternalBlob]],
    string
  >,
  'publishBlogPost' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string, string], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'unpublishBlogPost' : ActorMethod<[string], undefined>,
  'updateAddress' : ActorMethod<[Address, Address], undefined>,
  'updateBlogPost' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      MedicineCategory,
      boolean,
      boolean,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];